### PR TITLE
Fix/#6463 audit log implementation

### LINKED ISSUE #6463: QA Certifcation API Audit Implementation
Based on the solution that was created in #4732, finish implementation of the audit records for the qa certification API. The implementation focuses only on the workspace methods. The events include operations that create, update, delete or retrieve records. The audits should contain the standard meta data identified in #4732 and the following items for each endpoint.

## QA Certification

GET
/qa-certification-mgmt/workspace/export
**eventName**:"Exported workspace QA Certification records"
**moreInfo**:
    \<all supplied request parameters\>

POST
/qa-certification-mgmt/workspace/import
**eventName**:"Imported workspace QA Certification records"
**moreInfo**:
    orisCode
    testNumber(s)

GET
/qa-certification-mgmt/workspace/cert-events
**eventName**:"Retrieved workspace certification event records"
**moreInfo**:
    orisCodes
    monPlanIds
    quarters

GET
/qa-certification-mgmt/workspace/test-summary
**eventName**:"Retrieved workspace test summary records"
**moreInfo**:
    orisCodes
    monPlanIds
    quarters

GET
/qa-certification-mgmt/workspace/test-extension-exemption
**eventName**:"Retrieved test extension exemption records"
**moreInfo**:
    orisCodes
    monPlanIds
    quarters

GET
/qa-certification-mgmt/workspace/mats-bulk-file
**eventName**:"Retrieved MATS bulk file records"
**moreInfo**:
    orisCodes
    monPlanIds
    quarters

## Test Summary

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary
**eventName**:"Retrieved test summary records for location"
**moreInfo**:
    locId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary
**eventName**:"Created test summary record for location"
**moreInfo**:
    locId

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{id}
**eventName**:"Retrieved test summary record by ID for location"
**moreInfo**:
    locId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{id}
**eventName**:"Updated test summary record by ID for location"
**moreInfo**:
    locId
    id

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{id}
**eventName**:"Deleted test summary record by ID for location"
**moreInfo**:
    locId
    id

## Linearity Summary

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/linearities
**eventName**:"Retrieved linearity records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/linearities
**eventName**:"Created linearity record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/linearities/{id}
**eventName**:"Retrieved linearity record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/linearities/{id}
**eventName**:"Updated linearity record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/linearities/{id}
**eventName**:"Deleted linearity record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

## Linearity Injection

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/linearities/{linSumId}/injections
**eventName**:"Retrieved injection records for linearity summary"
**moreInfo**:
    locId
    testSumId
    linSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/linearities/{linSumId}/injections
**eventName**:"Created injection record for linearity summary"
**moreInfo**:
    locId
    testSumId
    linSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/linearities/{linSumId}/injections/{id}
**eventName**:"Retrieved injection record by ID for linearity summary"
**moreInfo**:
    locId
    testSumId
    linSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/linearities/{linSumId}/injections/{id}
**eventName**:"Updated injection record by ID for linearity summary"
**moreInfo**:
    locId
    testSumId
    linSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/linearities/{linSumId}/injections/{id}
**eventName**:"Deleted injection record by ID for linearity summary"
**moreInfo**:
    locId
    testSumId
    linSumId
    id

## Protocol Gas

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/protocol-gases
**eventName**:"Retrieved protocol gas records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/protocol-gases
**eventName**:"Created protocol gas record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/protocol-gases/{id}
**eventName**:"Retrieved protocol gas record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/protocol-gases/{id}
**eventName**:"Updated protocol gas record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/protocol-gases/{id}
**eventName**:"Deleted protocol gas record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

## RATA

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata
**eventName**:"Retrieved RATA records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata
**eventName**:"Created RATA record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{id}
**eventName**:"Retrieved RATA record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{id}
**eventName**:"Updated RATA record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{id}
**eventName**:"Deleted RATA record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

## Test Qualification

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/test-qualifications
**eventName**:"Retrieved test qualification records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/test-qualifications
**eventName**:"Created test qualification record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/test-qualifications/{id}
**eventName**:"Retrieved test qualification record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/test-qualifications/{id}
**eventName**:"Updated test qualification record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/test-qualifications/{id}
**eventName**:"Deleted test qualification record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

## Fuel Flow To Load Test

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flow-to-load-tests
**eventName**:"Retrieved fuel flow to load test records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flow-to-load-tests
**eventName**:"Created fuel flow to load test record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flow-to-load-tests/{id}
**eventName**:"Retrieved fuel flow to load test record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flow-to-load-tests/{id}
**eventName**:"Updated fuel flow to load test record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flow-to-load-tests/{id}
**eventName**:"Deleted fuel flow to load test record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

## Fuel Flow To Load Baseline

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flow-to-load-baselines
**eventName**:"Retrieved fuel flow to load baseline records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flow-to-load-baselines
**eventName**:"Created fuel flow to load baseline record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flow-to-load-baselines/{id}
**eventName**:"Retrieved fuel flow to load baseline record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flow-to-load-baselines/{id}
**eventName**:"Updated fuel flow to load baseline record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flow-to-load-baselines/{id}
**eventName**:"Deleted fuel flow to load baseline record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

## Fuel Flowmeter Accuracy

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flowmeter-accuracies
**eventName**:"Retrieved fuel flowmeter accuracy records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flowmeter-accuracies
**eventName**:"Created fuel flowmeter accuracy record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flowmeter-accuracies/{id}
**eventName**:"Retrieved fuel flowmeter accuracy record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flowmeter-accuracies/{id}
**eventName**:"Updated fuel flowmeter accuracy record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/fuel-flowmeter-accuracies/{id}
**eventName**:"Deleted fuel flowmeter accuracy record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

## Flow To Load Check

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/flow-to-load-checks
**eventName**:"Retrieved flow to load check records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/flow-to-load-checks
**eventName**:"Created flow to load check record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/flow-to-load-checks/{id}
**eventName**:"Retrieved flow to load check record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/flow-to-load-checks/{id}
**eventName**:"Updated flow to load check record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/flow-to-load-checks/{id}
**eventName**:"Deleted flow to load check record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

## Flow To Load Reference

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/flow-to-load-references
**eventName**:"Retrieved flow to load reference records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/flow-to-load-references
**eventName**:"Created flow to load reference record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/flow-to-load-references/{id}
**eventName**:"Retrieved flow to load reference record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/flow-to-load-references/{id}
**eventName**:"Updated flow to load reference record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/flow-to-load-references/{id}
**eventName**:"Deleted flow to load reference record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

## Air Emission Testing

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/air-emission-testings
**eventName**:"Retrieved air emission testing records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/air-emission-testings
**eventName**:"Created air emission testing record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/air-emission-testings/{id}
**eventName**:"Retrieved air emission testing record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/air-emission-testings/{id}
**eventName**:"Updated air emission testing record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/air-emission-testings/{id}
**eventName**:"Deleted air emission testing record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

## Appendix E Correlation Test Summary

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries
**eventName**:"Retrieved appendix E correlation test summaries for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries
**eventName**:"Created appendix E correlation test summary for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{id}
**eventName**:"Retrieved appendix E correlation test summary by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{id}
**eventName**:"Updated appendix E correlation test summary by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{id}
**eventName**:"Deleted appendix E correlation test summary by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs
**eventName**:"Retrieved appendix E correlation test runs for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs
**eventName**:"Created appendix E correlation test run for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{id}
**eventName**:"Retrieved appendix E correlation test run by ID for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{id}
**eventName**:"Updated appendix E correlation test run by ID for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{id}
**eventName**:"Deleted appendix E correlation test run by ID for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    id

## Appendix E Heat Input From Oil

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{appECorrTestRunId}/appendix-e-heat-input-from-oils
**eventName**:"Retrieved appendix E heat input from oils for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    appECorrTestRunId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{appECorrTestRunId}/appendix-e-heat-input-from-oils
**eventName**:"Created appendix E heat input from oil for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    appECorrTestRunId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{appECorrTestRunId}/appendix-e-heat-input-from-oils/{id}
**eventName**:"Retrieved appendix E heat input from oil by ID for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    appECorrTestRunId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{appECorrTestRunId}/appendix-e-heat-input-from-oils/{id}
**eventName**:"Updated appendix E heat input from oil by ID for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    appECorrTestRunId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{appECorrTestRunId}/appendix-e-heat-input-from-oils/{id}
**eventName**:"Deleted appendix E heat input from oil by ID for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    appECorrTestRunId
    id

## Appendix E Heat Input From Gas

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{appECorrTestRunId}/appendix-e-heat-input-from-gases
**eventName**:"Retrieved appendix E heat input from gases for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    appECorrTestRunId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{appECorrTestRunId}/appendix-e-heat-input-from-gases
**eventName**:"Created appendix E heat input from gas for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    appECorrTestRunId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{appECorrTestRunId}/appendix-e-heat-input-from-gases/{id}
**eventName**:"Retrieved appendix E heat input from gas by ID for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    appECorrTestRunId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{appECorrTestRunId}/appendix-e-heat-input-from-gases/{id}
**eventName**:"Updated appendix E heat input from gas by ID for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    appECorrTestRunId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/appendix-e-correlation-test-summaries/{appECorrTestSumId}/appendix-e-correlation-test-runs/{appECorrTestRunId}/appendix-e-heat-input-from-gases/{id}
**eventName**:"Deleted appendix E heat input from gas by ID for test summary"
**moreInfo**:
    locId
    testSumId
    appECorrTestSumId
    appECorrTestRunId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/calibration-injections
**eventName**:"Retrieved calibration injection records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/calibration-injections
**eventName**:"Created calibration injection record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/calibration-injections/{id}
**eventName**:"Retrieved calibration injection record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/calibration-injections/{id}
**eventName**:"Updated calibration injection record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/calibration-injections/{id}
**eventName**:"Deleted calibration injection record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/online-offline-calibration
**eventName**:"Retrieved online offline calibration records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/online-offline-calibration
**eventName**:"Created online offline calibration record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/online-offline-calibration/{id}
**eventName**:"Retrieved online offline calibration record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/online-offline-calibration/{id}
**eventName**:"Updated online offline calibration record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/online-offline-calibration/{id}
**eventName**:"Deleted online offline calibration record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/cycle-time-summaries
**eventName**:"Retrieved cycle time summary records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/cycle-time-summaries
**eventName**:"Created cycle time summary record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/cycle-time-summaries/{id}
**eventName**:"Retrieved cycle time summary record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/cycle-time-summaries/{id}
**eventName**:"Updated cycle time summary record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/cycle-time-summaries/{id}
**eventName**:"Deleted cycle time summary record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{cycleTimeSumId}/cycle-time-injections
**eventName**:"Retrieved cycle time injection records for test summary"
**moreInfo**:
    locId
    cycleTimeSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{cycleTimeSumId}/cycle-time-injections
**eventName**:"Created cycle time injection record for test summary"
**moreInfo**:
    locId
    cycleTimeSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{cycleTimeSumId}/cycle-time-injections/{id}
**eventName**:"Retrieved cycle time injection record by ID for test summary"
**moreInfo**:
    locId
    cycleTimeSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{cycleTimeSumId}/cycle-time-injections/{id}
**eventName**:"Updated cycle time injection record by ID for test summary"
**moreInfo**:
    locId
    cycleTimeSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{cycleTimeSumId}/cycle-time-injections/{id}
**eventName**:"Deleted cycle time injection record by ID for test summary"
**moreInfo**:
    locId
    cycleTimeSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/unit-default-tests
**eventName**:"Retrieved unit default test records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/unit-default-tests
**eventName**:"Created unit default test record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/unit-default-tests/{id}
**eventName**:"Retrieved unit default test record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/unit-default-tests/{id}
**eventName**:"Updated unit default test record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/unit-default-tests/{id}
**eventName**:"Deleted unit default test record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/unit-default-tests/{unitDefaultTestSumId}/unit-default-test-runs
**eventName**:"Retrieved unit default test run records for test summary"
**moreInfo**:
    locId
    testSumId
    unitDefaultTestSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/unit-default-tests/{unitDefaultTestSumId}/unit-default-test-runs
**eventName**:"Created unit default test run record for test summary"
**moreInfo**:
    locId
    testSumId
    unitDefaultTestSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/unit-default-tests/{unitDefaultTestSumId}/unit-default-test-runs/{id}
**eventName**:"Retrieved unit default test run record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    unitDefaultTestSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/unit-default-tests/{unitDefaultTestSumId}/unit-default-test-runs/{id}
**eventName**:"Updated unit default test run record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    unitDefaultTestSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/unit-default-tests/{unitDefaultTestSumId}/unit-default-test-runs/{id}
**eventName**:"Deleted unit default test run record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    unitDefaultTestSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/transmitter-transducer-accuracy
**eventName**:"Retrieved transmitter transducer accuracy records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/transmitter-transducer-accuracy
**eventName**:"Created transmitter transducer accuracy record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/transmitter-transducer-accuracy/{id}
**eventName**:"Retrieved transmitter transducer accuracy record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/transmitter-transducer-accuracy/{id}
**eventName**:"Updated transmitter transducer accuracy record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/transmitter-transducer-accuracy/{id}
**eventName**:"Deleted transmitter transducer accuracy record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/hg-summaries
**eventName**:"Retrieved Hg summary records for test summary"
**moreInfo**:
    locId
    testSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/hg-summaries
**eventName**:"Created Hg summary record for test summary"
**moreInfo**:
    locId
    testSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/hg-summaries/{id}
**eventName**:"Retrieved Hg summary record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/hg-summaries/{id}
**eventName**:"Updated Hg summary record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/hg-summaries/{id}
**eventName**:"Deleted Hg summary record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/hg-summaries/{hgTestSumId}/hg-injections
**eventName**:"Retrieved Hg injection records for test summary"
**moreInfo**:
    locId
    testSumId
    hgTestSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/hg-summaries/{hgTestSumId}/hg-injections
**eventName**:"Created Hg injection record for test summary"
**moreInfo**:
    locId
    testSumId
    hgTestSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/hg-summaries/{hgTestSumId}/hg-injections/{id}
**eventName**:"Retrieved Hg injection record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    hgTestSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/hg-summaries/{hgTestSumId}/hg-injections/{id}
**eventName**:"Updated Hg injection record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    hgTestSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/hg-summaries/{hgTestSumId}/hg-injections/{id}
**eventName**:"Deleted Hg injection record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    hgTestSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries
**eventName**:"Retrieved RATA summary records for test summary"
**moreInfo**:
    locId
    testSumId
    rataId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries
**eventName**:"Created RATA summary record for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{id}
**eventName**:"Retrieved RATA summary record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{id}
**eventName**:"Updated RATA summary record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{id}
**eventName**:"Deleted RATA summary record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs
**eventName**:"Retrieved RATA run records for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs
**eventName**:"Created RATA run record for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{id}
**eventName**:"Retrieved RATA run record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{id}
**eventName**:"Updated RATA run record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{id}
**eventName**:"Deleted RATA run record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{rataRunId}/flow-rata-runs
**eventName**:"Retrieved flow RATA run records for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    rataRunId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{rataRunId}/flow-rata-runs
**eventName**:"Created flow RATA run record for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    rataRunId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{rataRunId}/flow-rata-runs/{id}
**eventName**:"Retrieved flow RATA run record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    rataRunId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{rataRunId}/flow-rata-runs/{id}
**eventName**:"Updated flow RATA run record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    rataRunId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{rataRunId}/flow-rata-runs/{id}
**eventName**:"Deleted flow RATA run record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    rataRunId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{rataRunId}/flow-rata-runs/{flowRataRunId}/rata-traverses
**eventName**:"Retrieved RATA traverse records for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    rataRunId
    flowRataRunId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{rataRunId}/flow-rata-runs/{flowRataRunId}/rata-traverses
**eventName**:"Created RATA traverse record for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    rataRunId
    flowRataRunId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{rataRunId}/flow-rata-runs/{flowRataRunId}/rata-traverses/{id}
**eventName**:"Retrieved RATA traverse record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    rataRunId
    flowRataRunId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{rataRunId}/flow-rata-runs/{flowRataRunId}/rata-traverses/{id}
**eventName**:"Updated RATA traverse record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    rataRunId
    flowRataRunId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-summary/{testSumId}/rata/{rataId}/rata-summaries/{rataSumId}/rata-runs/{rataRunId}/flow-rata-runs/{flowRataRunId}/rata-traverses/{id}
**eventName**:"Deleted RATA traverse record by ID for test summary"
**moreInfo**:
    locId
    testSumId
    rataId
    rataSumId
    rataRunId
    flowRataRunId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/qa-certification-events
**eventName**:"Retrieved QA certification events for location"
**moreInfo**:
    locId

POST
/qa-certification-mgmt/workspace/locations/{locId}/qa-certification-events
**eventName**:"Created QA certification event for location"
**moreInfo**:
    locId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/qa-certification-events/{id}
**eventName**:"Retrieved QA certification event by ID for location"
**moreInfo**:
    locId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/qa-certification-events/{id}
**eventName**:"Updated QA certification event by ID for location"
**moreInfo**:
    locId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/qa-certification-events/{id}
**eventName**:"Deleted QA certification event by ID for location"
**moreInfo**:
    locId
    id

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-extension-exemptions
**eventName**:"Retrieved test extension exemption records for location"
**moreInfo**:
    locId

POST
/qa-certification-mgmt/workspace/locations/{locId}/test-extension-exemptions
**eventName**:"Created test extension exemption record for location"
**moreInfo**:
    locId
    \<record\>

GET
/qa-certification-mgmt/workspace/locations/{locId}/test-extension-exemptions/{id}
**eventName**:"Retrieved test extension exemption record by ID for location"
**moreInfo**:
    locId
    id

PUT
/qa-certification-mgmt/workspace/locations/{locId}/test-extension-exemptions/{id}
**eventName**:"Updated test extension exemption record by ID for location"
**moreInfo**:
    locId
    id
    \<record\>

DELETE
/qa-certification-mgmt/workspace/locations/{locId}/test-extension-exemptions/{id}
**eventName**:"Deleted test extension exemption record by ID for location"
**moreInfo**:
    locId
    id

### PR DESCRIPTION
**Pull request by ergjustin**
## Ticket
[QA Certifcation API Audit Implementation](https://github.com/US-EPA-CAMD/easey-ui/issues/6463)

## Changes

- Audit log implementation

### CODE REVIEW

File: src/linearity-injection-workspace/linearity-injection.controller.ts [hunk 1]
```diff
@@ -153,6 +171,11 @@ export class LinearityInjectionWorkspaceController {
   @ApiOkResponse({
     description: 'Deletes a Linearity Injection record from the workspace',
   })
+  @AuditLog({
+    label: 'Deleted injection record by ID for linearity summary',
+    requestParamsOutFields: ['locId', 'testSumId', 'linSumId', 'id'],
+    responseBodyOutFields: '*'
```
Comment (maxdiebold-erg) [inline src/linearity-injection-workspace/linearity-injection.controller.ts]: As noted elsewhere, this endpoint does not return a response, so this line won't have an effect.
```suggestion
```

File: src/fuel-flow-to-load-test-workspace/fuel-flow-to-load-test-workspace.controller.ts [hunk 2]
```diff
@@ -138,6 +156,11 @@ export class FuelFlowToLoadTestWorkspaceController {
   @ApiOkResponse({
     description: 'Deletes a Fuel Flow To Load Test record from the workspace',
   })
+  @AuditLog({
+    label: 'Deleted fuel flow to load test record by ID for test summary',
+    requestParamsOutFields: ['locId', 'testSumId', 'id'],
+    responseBodyOutFields: '*'
```
Comment (maxdiebold-erg) [inline src/fuel-flow-to-load-test-workspace/fuel-flow-to-load-test-workspace.controller.ts]: This endpoint does _not_ return the deleted record, so this won't log the deleted record. I think the ticket is in error about this, anyway, since it only specifies that the record should be returned for a couple of `DELETE` endpoints. I don't think it will cause an error leaving it, but just noting the discrepancy.
```suggestion
```

File: src/app-e-correlation-test-summary-workspace/app-e-correlation-test-summary-workspace.controller.ts [hunk 3]
```diff
@@ -143,6 +161,10 @@ export class AppendixETestSummaryWorkspaceController {
     description:
       'Deletes a workspace Appendix E Correlation Test Summary record',
   })
+  @AuditLog({
+    label: 'Deleted appendix E correlation test summary by ID for test summary',
+    requestParamsOutFields: ['locId', 'testSumId']
```
Comment (maxdiebold-erg) [inline src/app-e-correlation-test-summary-workspace/app-e-correlation-test-summary-workspace.controller.ts]: According to the ticket, this should return the `id`, too:
```suggestion
    requestParamsOutFields: ['id', 'locId', 'testSumId']
```

**Review by maxdiebold-erg — CHANGES_REQUESTED** [review]
Good work, that's a lot of endpoints! I found just one case where there is a field missing from the output, noted below, and I found a couple `DELETE` endpoints that may not function as expected.

**Review by maxdiebold-erg — APPROVED** [review]
Thanks for making those changes!
